# Generated by Django 5.0.1 on 2024-03-09 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid 11-digit phone number with digits only.', regex='^\\d{11}$')]),
        ),
    ]
